### ISSUE TITLE
plan no sulution found

### ISSUE THREAD

**Issue by huiwenzhang** [huiwenzhang/tiago-custom-pkgs#1]
### Description
This package is implemented a wrapper service node for Cartesian plan. Node complied successfully, however when the server node is called, plan failed every time. The server node stucks there and ROS throw errors as follows:
```
[ INFO] [1526006042.640520830, 4513.019000000]: arm_torso[SBLkConfigDefault]: Attempting to use default projection.
[ INFO] [1526006042.640839743, 4513.020000000]: arm_torso[SBLkConfigDefault]: Starting planning with 1 states already in datastructure
[ERROR] [1526006052.645057349, 4522.989000000]: arm_torso[SBLkConfigDefault]: Unable to sample any valid states for goal tree
[ INFO] [1526006052.645109296, 4522.989000000]: arm_torso[SBLkConfigDefault]: Created 1 (1 start + 0 goal) states in 1 cells (1 start + 0 goal)
[ INFO] [1526006052.645137657, 4522.989000000]: No solution found after 10.004544 seconds
[ INFO] [1526006052.649377088, 4522.993000000]: Unable to solve the planning problem
```
The strange point is: I execute the planing with a normal node instead of service node, all the initial state and the goal pose are set the same, planning is solved successfully.  

https://github.com/huiwenzhang/tiago-custom-pkgs/blob/3b069612efbf76945880d6ade45f9864fa1e9bbf/src/moveit_plan_service/src/cartesian_plan_server.cpp#L45

**Comment by jacknlliu** [comment]
Try to add some codes like the following lines in your `main()` function 
```cpp
#include <ros/ros.h>
#include <ros/callback_queue.h>
#include <ros/advertise_service_options.h>

int main(){
   // define a new callback queue for service callback
    ros::CallbackQueue srv_cb_queue;

    ros::AdvertiseServiceOptions ops = 
    ros::AdvertiseServiceOptions::create<SomeServiceType::ServericeType>(srv_name, 
                                        cb_function, ros::VoidPtr(),
                                        &srv_cb_queue);

    ros::ServiceServer your_srv = nh.advertiseService(ops);

    ros::AsyncSpinner async_spinner(1, &srv_cb_queue);
    async_spinner.start();

    while (){
     ....
    }
}
```

**Comment by huiwenzhang** [comment]
@jacknlliu  你这个估计行，昨晚我试着用多个异步线程`ros::AsyncSpinner spinner(2);`，然后就work了．不过我没搞清原因．

**Comment by jacknlliu** [comment]
There are inner callback queues in moveit, and it uses the global callback queue. When calling the service server, the callback queue can't response to the coming moveit inner callback event(current callback queue is busy, because current callback is not exit), so it's blocking. If assign more spinner, when main thread callback queue is busy, another spinner thread will process other things.
